/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package cholera

import cholera.styles.Styles
import cholera.views.MainView
import tornadofx.App

class App: App(MainView::class, Styles::class)